# Use the (faster) container-based infrastructure, see also
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: true
dist: bionic

language: go
go:
  - "1.13"

script:
  # Check whether files are syntactically correct.
  - "gofmt -l $(find . -name '*.go' | tr '\\n' ' ') >/dev/null"
  # Check whether files were not gofmt'ed.
  - "gosrc=$(find . -name '*.go' | tr '\\n' ' '); [ $(gofmt -l $gosrc 2>&- | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $gosrc 2>&-; false)"
  - go vet .
  - go test ./...
  - go test -c github.com/sbezverk/nftableslib
  - go build -a -o ./bin/e2e ./e2e/main.go
  - sudo ./bin/e2e
